### ISSUE TITLE
Feature request: Schedule internet block between certain times of day, not the whole day

### ISSUE THREAD

**Issue by hungmn** [firewalla/firewalla#1055]
Hello,

One main reason I bought firewalla is the ability to restrict Internet usage for my kids.  But the current option to block is only days of the week, not hours of the day.  So it is not practical.

Please add options for Block during Workdays/Weekends with start and end hours.  E.g. I want to restrict Internet access on after 9:00pm and before 6:00am every day.

If not, I would appreciate some tutorial to ssh to the box and add some crond jobs to enable/disable the rules, that would be cool too.

Thanks,
Hung

**Comment by MelvinTo** [comment]
Thanks for the feedback. The backend already supported this (in beta), if you would like to try it out, please send email to help@firewalla.com, we will follow up there.

We do have plan to implement this in the app, but not in the near future due to lacking of enough development resource. :(

Melvin

**Comment by MelvinTo** [comment]
already supported in latest release
